spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
   basename: validation
  thymeleaf:
    cache: false
    prefix: file:./src/main/resources/templates/
    check-template: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

