spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  messages:
   basename: validation
  thymeleaf:
    cache: false
    prefix: file:./src/main/resources/templates/
    check-template: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

